### ISSUE TITLE
Introduire l'usage du "They"

### ISSUE THREAD

**Issue by ipante** [ncarette/dailyroutine#10]
L'usage de They peut surprendre les personnes peu familières avec l'usage élargi de ce pronom personnel. Si votre projet entend être partagé avec la population générale, une brève note à ce sujet serait la bienvenue.

**Comment by ncarette** [comment]
Info box ajoutée pour expliquer le choix et l'usage, elle s'ouvre via deux liens : un dans la bar en haut à droite, un directement dans la première occurence de they dans le texte.

**Comment by ipante** [comment]
Splendide !

**Comment by ipante** [comment]
J'ai saisi la validation ;)
