### ISSUE TITLE
ajouter une fin au projet

### ISSUE THREAD

**Issue by ipante** [ncarette/dailyroutine#9]
A l'heure actuelle, le projet ne donne pas le sentiment d'arriver à son terme. Même si des développements futurs sont envisagés, il est essentiel de marquer la fin, d'une manière ou d'une autre. Idéalement, des indications devraient être fournies pour inviter à la rejouabilité (par exemple en renseignant sur l'état des jauges sous une forme textuelle et en invitant à changer son parcours ?)

**Comment by ncarette** [comment]
des fins plus développées et mises en page ont été ajoutées. Elles contiennent un bilan de l'histoire (bref mais assez utile) ainsi qu'une adresse au lecteur.
